#!/bin/sh

echo "Creating Migrations..."
python manage.py makemigrations weather_api
python manage.py migrate
echo "Dumping Data"
python manage.py create || { echo "Create command failed"; exit 1; }
python manage.py runserver 0.0.0.0:8000